config/routes.rb
SampleApp::Application.routes.draw do
  get "sessions/new"

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :sessions,      :only => [:new, :create, :destroy]
  resources :microposts,    :only => [:create, :destroy]
  resources :relationships, :only => [:create, :destroy]

  match '/signup',  :to => 'users#new'
  match '/signin',  :to => 'sessions#new'
  match '/signout', :to => 'sessions#destroy'

  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/news',    :to => 'pages#news'
  
  root :to => 'pages#home'











end

app/views/pages/about.html.erb
<h1>About</h1>
<p>YATC, which is short for <span style="color: rgb(152, 12, 39)">Yet another Twitter clone</span>, is an exercise in creating
a Ruby on Rails web application. You can use this web application to write small posts (microposts) about yourself, what you're
going to do, what you just did, or whatever comes to your mind! You can follow what other people are doing, and in turn, other
people can follow you.</p>
<p>There is still a lot more to be done to YATC, however. I plan on adding more features to this web application in the future.
Here's what I'm thinking about so far:</p>
<ul><li>A private messaging system</li><li>Users getting notified via e-mail whenever someone follows them</li>
<li>A site-wide search feature so that users can find one another</li><li>RSS feeds</li><li>...and the list goes on.</li></ul>
<p>Although YATC still has a long way to go before becoming the next Twitter, please feel free to tell your family and
friends about this web application. My hope is that one day, it will have just as much users as the original. :-)</p>
<p>Regards,<br />BJ Peter DeLaCruz<br /><span style="font-style: italic;">Developer</span></p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>BJ Peter DeLaCruz can be contacted at:<br /><br />

<span style="font-weight: bold">E-mail:</span><br />
<a href="mailto:bjpeter@hawaii.edu">bjpeter@hawaii.edu</a><br /><br />
<span style="font-weight: bold">Website:</span><br />
<a href="http://www2.hawaii.edu/~bjpeter" target="_blank">http://www2.hawaii.edu/~bjpeter</a><br /><br />
<span style="font-weight: bold">Mailing Address:</span><br />
Department of Information and Computer Sciences<br />
University of Hawaii at Manoa<br />
1680 Campus Road<br />
Honolulu, HI 96822<br /><br />
<span style="font-weight: bold">Blogs:</span><br />
<a href="http://thetravelingcs.blogspot.com" target="_blank">The Traveling Computer Scientist</a>
&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;&nbsp;<a href="http://bpdelacruz.blogspot.com" target="_blank">My Software Engineering Journal</a>

</p>

app/views/pages/help.html.erb
<h1>Help</h1>
<p>To sign up for an account on YATC, all you need to do is supply a name for yourself and a valid e-mail address. Once you're signed in...</p>
<ul><li>Click on <%= link_to "Home", root_path %> to write a new micropost. Here, you can also view all the microposts of those you
are following, and yours too.</li>
<li>Head over to <% if signed_in? %><%= link_to "Users", users_path %><% else %>Users<% end %> to see who else is signed up on YATC. Click on their
names or profile pictures to view their profiles. To follow another user, head over to his or her profile page and click on the Follow button below
his or her profile picture. To unfollow someone, simply click on the Unfollow button, also on the user's profile page.</li>
<li>To view your own profile, check out the <% if signed_in? %><%= link_to "Profile", current_user %><% else %>Profile<% end %> page. Below your
profile picture is a status feed that contains only your microposts. If you want see all the people whom you are following, click on the
following link on the right-hand side of your profile page. To list those who are following you, click on the appropriately named followers link.</li>
<li>You can change your name, e-mail address, password, and avatar via the <% if signed_in? %><%= link_to "Settings", edit_user_path(current_user) %>
<% else %>Settings<% end %> page. Avatars are hosted on <a href="http://www.gravatar.com" target="_blank">Gravatar</a>, so to upload your own and use
it on YATC, or use an avatar that is already on Gravatar, you have to sign up for an account with them first.</li></ul>
<p>That's about it! If you have any questions or comments about YATC, please <%= link_to "contact", contact_path %> me. I'd be more than happy to hear from you!</p>
<p>Regards,<br />BJ Peter DeLaCruz<br /><span style="font-style: italic;">Developer</span></p>

app/views/pages/home.html.erb
<% if signed_in? %>
  <table class="front" summary="For signed-in users">
    <tr>
      <td class="main">
        <h1 class="micropost">What's up?</h1>
        <%= render 'shared/micropost_form' %>
        <%= render 'shared/feed' %>
      </td>
      <td class="sidebar round">
        <%= render 'shared/user_info' %>
        <%= render 'shared/stats' %>
      </td>
    </tr>
  </table>
<% else %>
  <h1>Welcome!</h1>

  <p>This is the home page for the <span style="color: rgb(152, 12, 39);">Yet another Twitter clone</span> web application.</p>

  <%= link_to "Sign up now!", signup_path, :class => "signup_button round" %><br />
  <div style="text-align: center"><p>Or <%= link_to "sign in", signin_path %> if you already have an account.</p></div>
<% end %>

app/views/pages/news.html.erb
<h1>News</h1>
<p><span style="font-weight: bold">September 27, 2010</span> Version 1.0 of YATC is released.</p>